// @vitest-environment node
/**
 * The point of this file: stop the two "ends" of a share link — the browser
 * and this server — from silently drifting apart. Both actually call the
 * same `seal`/`sealBundle`/`open` in `src/crypto.ts`, so a naive round trip
 * through only this server would prove nothing beyond "this server agrees
 * with itself." Every case here instead crosses the boundary on purpose:
 * bytes produced by one side's *wrapping* code (this server's tool handlers,
 * or a payload built exactly the way `src/share.ts`'s browser UI builds one)
 * are read back by the other side's.
 *
 * `test/fixtures/share-v2-compat.json` — sealed by the pre-T5 `crypto.ts`,
 * per its own header comment — is the one input in this file that is not
 * generated by anything in this repository's current `HEAD`, and is exactly
 * what `docs/task-specs/T7.md` asks this test to include.
 */
import "../../mcp/locale.js";

import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import { createMcpServer } from "../../mcp/build-server.js";
import { open, seal, sealBundle } from "../../src/crypto.js";
import type { BundlePayload, SharePayload } from "../../src/crypto.js";
import fixture from "../fixtures/share-v2-compat.json" with { type: "json" };
import { createStubBackend } from "./stub-backend.js";

const ORIGIN = "https://stub.example";
const HEX_SECRET = "c".repeat(64);

let fetchSpy: ReturnType<typeof vi.spyOn> | undefined;
beforeEach(() => {
  fetchSpy = vi.spyOn(globalThis, "fetch").mockImplementation(() => {
    throw new Error("cross-compat tests must never call the real fetch");
  });
});
afterEach(() => {
  fetchSpy?.mockRestore();
});

async function connectedClient(backend: ReturnType<typeof createStubBackend>) {
  const server = createMcpServer({ fetchImpl: backend.fetchImpl, defaultOrigin: ORIGIN });
  const [clientTransport, serverTransport] = InMemoryTransport.createLinkedPair();
  const client = new Client({ name: "cross-compat-test", version: "0.0.0" });
  await Promise.all([client.connect(clientTransport), server.connect(serverTransport)]);
  return client;
}

function asToolResult(result: object) {
  if (!("content" in result)) throw new Error("expected an ordinary tool result, got a task result");
  return result as { content: { type: string; text?: string }[]; structuredContent?: Record<string, unknown>; isError?: boolean };
}

describe("this server mints, the browser's own open() reads it back", () => {
  it("a single document", async () => {
    const backend = createStubBackend(ORIGIN);
    const client = await connectedClient(backend);

    const text = '{"data":{"type":"trips","id":"9"}}';
    const shared = asToolResult(
      await client.callTool({
        name: "share",
        arguments: { documents: [{ label: "trip.json", text }], secret: HEX_SECRET },
      }),
    );
    const id = shared.structuredContent!.id as number;

    const blob = new Uint8Array(await (await backend.fetchImpl(`${ORIGIN}/api/shares/${id}`)).arrayBuffer());
    expect(blob[0]).toBe(2); // version byte: single document, never a bundle

    const opened = (await open(blob as Uint8Array<ArrayBuffer>, HEX_SECRET)) as SharePayload;
    expect(opened.text).toBe(text);
    expect(opened.label).toBe("trip.json");
    expect(typeof opened.savedAt).toBe("number");
  });

  it("a bundle, every entry intact", async () => {
    const backend = createStubBackend(ORIGIN);
    const client = await connectedClient(backend);

    const shared = asToolResult(
      await client.callTool({
        name: "share",
        arguments: {
          documents: [
            { label: "a.json", text: "1", exchange: { method: "GET" } },
            { label: "b.json", text: "2" },
          ],
          secret: HEX_SECRET,
        },
      }),
    );
    const id = shared.structuredContent!.id as number;

    const blob = new Uint8Array(await (await backend.fetchImpl(`${ORIGIN}/api/shares/${id}`)).arrayBuffer());
    expect(blob[0]).toBe(3); // version byte: bundle

    const opened = (await open(blob as Uint8Array<ArrayBuffer>, HEX_SECRET)) as BundlePayload;
    expect(opened.kind).toBe("bundle");
    expect(opened.documents).toHaveLength(2);
    expect(opened.documents[0]).toMatchObject({ label: "a.json", text: "1", exchange: { method: "GET" } });
    expect(opened.documents[1]).toMatchObject({ label: "b.json", text: "2" });
  });
});

describe("a payload built the way src/share.ts's browser UI builds one, this server's read tool reads it back", () => {
  it("a single document sealed with the bare seal()", async () => {
    const backend = createStubBackend(ORIGIN);
    const client = await connectedClient(backend);

    // Exactly the shape `openShareModal` in src/share.ts constructs: no
    // `kind` field, `text`/`label`/`savedAt` only.
    const payload: SharePayload = { text: '{"data":null}', label: "browser.json", savedAt: 1_700_000_000_000 };
    const blob = await seal(payload, HEX_SECRET);
    await backend.fetchImpl(`${ORIGIN}/api/shares?lifetime=1d`, {
      method: "POST",
      headers: { "content-type": "application/octet-stream" },
      body: blob,
    });

    const result = asToolResult(await client.callTool({ name: "read", arguments: { id: 1, secret: HEX_SECRET } }));
    expect(result.isError).not.toBe(true);
    expect(result.structuredContent).toMatchObject({
      kind: "document",
      label: "browser.json",
      savedAt: 1_700_000_000_000,
      text: '{"data":null}',
    });
  });

  it("a bundle sealed with the bare sealBundle(), every document present", async () => {
    const backend = createStubBackend(ORIGIN);
    const client = await connectedClient(backend);

    const payload: BundlePayload = {
      kind: "bundle",
      savedAt: 1_700_000_000_000,
      documents: [
        { label: "x.json", text: "10" },
        { label: "y.json", text: "20" },
        { label: "z.json", text: "30" },
      ],
    };
    const blob = await sealBundle(payload, HEX_SECRET);
    await backend.fetchImpl(`${ORIGIN}/api/shares?lifetime=1d`, {
      method: "POST",
      headers: { "content-type": "application/octet-stream" },
      body: blob,
    });

    const result = asToolResult(await client.callTool({ name: "read", arguments: { id: 1, secret: HEX_SECRET } }));
    expect(result.structuredContent?.kind).toBe("bundle");
    const documents = result.structuredContent?.documents as { label: string; text: string }[];
    expect(documents).toHaveLength(3);
    expect(documents.map((d) => d.label)).toEqual(["x.json", "y.json", "z.json"]);
  });
});

describe("the T5 compatibility fixture", () => {
  it("opens through the exact open() this server imports, unmodified", async () => {
    // This fixture's own secret ("fixtureT5x", 10 characters) is not 64
    // lowercase hex, so it cannot flow through this server's *registered*
    // `read` tool — that 64-hex requirement is this MCP surface's own
    // deliberate policy (docs/task-specs/T7.md; consistent between `share`
    // and `read` by construction, since both call the same
    // `mcp/validate.ts#assertValidSecret`), not a property of the shared
    // envelope format. What this fixture actually guards is one level
    // underneath that policy: that `src/crypto.ts`'s `open` — the exact
    // function `mcp/build-server.ts` imports and calls — has not drifted
    // from what sealed a real link before bundles or this server existed.
    // Calling it directly, as done here, is what proves that.
    const blob = new Uint8Array(Buffer.from(fixture.blobBase64, "base64")) as Uint8Array<ArrayBuffer>;
    const opened = (await open(blob, fixture.secret)) as SharePayload;

    expect(opened.text).toBe(fixture.payload.text);
    expect(opened.label).toBe(fixture.payload.label);
    expect(opened.savedAt).toBe(fixture.payload.savedAt);
  });
});
